---
stages:
  - lint
  - molecule

variables:
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

lint:
  stage: lint
  image: veselahouba/molecule
  script:
    - shellcheck_wrapper
    - flake8
    - yamllint .
    - ansible-lint

molecule_legacy:
  stage: molecule
  image: veselahouba/molecule
  script:
    - ansible --version
    - ./ci/prepare-dependencies.sh
    - molecule test --scenario-name=default
    - molecule test --scenario-name=compose
    - molecule test --scenario-name=container
  parallel:
    matrix:
      - MOLECULE_IMAGE:
          - debian-9

molecule:
  stage: molecule
  image: veselahouba/molecule
  script:
    - ansible --version
    - ./ci/prepare-dependencies.sh
    - molecule test --all
  parallel:
    matrix:
      - MOLECULE_IMAGE:
          - debian-10
          - ubuntu-16.04
          - ubuntu-18.04
          - ubuntu-20.04
