---
dependency:
  name: galaxy
driver:
  name: hetznercloud
platforms:
  - name: docker-container-${MOLECULE_IMAGE}
    server_type: cx11
    image: ${MOLECULE_IMAGE}
provisioner:
  name: ansible
verifier:
  name: testinfra
